### ISSUE TITLE
Stations not showing outside region 2

### ISSUE THREAD

**Issue by rwilkes1** [ices-tools-prod/COMPEAT#17]
Hi,
When you select the stations tab they only show for region 2- North sea.  No stations for other regions

**Comment by HjalteParner** [comment]
Hi Robert,

You are correct!

Currently only stations for the first 20000 station samples are shown in the map because of performance issues with the way it's currently implemented.

The plan is to show all stations on the map, and likewise the samples associated with each station when clicked in an associated table below.

**Comment by HjalteParner** [comment]
The system now shows all stations for the different datatypes within the station map
